Repository kleveross/klever-web, pull requests merged in 2020-11, with the labels that each got.

#1 feat(klever-web): init project
  .dockerignore
  .editorconfig
  .env
  .gitignore
  .prettierignore
  .prettierrc
  .umirc.ts
  Dockerfile
  OWNERS
  README.md
  app.js
  package.json
  tsconfig.json
  typings.d.ts
  yarn.lock
Labels: lgtm, release-note-none, size/XXL

#4 chore(*): add install docs and scripts
  CONTRIBUTING.md
  LICENSE
  README.md
  README_zh.md
  docs/docs_zh/installation.md
  docs/installation.md
  manifests/klever-web/.helmignore
  manifests/klever-web/Chart.yaml
  manifests/klever-web/templates/NOTES.txt
  manifests/klever-web/templates/_helpers.tpl
  manifests/klever-web/templates/deployment.yaml
  manifests/klever-web/templates/service.yaml
  manifests/klever-web/values.yaml
  scripts/installation/install.sh
Labels: do-not-merge/work-in-progress, release-note-none, size/XL

#5 feat(publish): add publish github action
  .github/workflows/publish.yml
Labels: release-note-none, size/S

#6 fix(actions): fix publish action
  .github/workflows/publish.yml
Labels: release-note-none, size/XS

#7 Fix(manifests): fix helm install charts
  manifests/klever-web/templates/deployment.yaml
  manifests/klever-web/templates/service.yaml
  manifests/klever-web/values.yaml
Labels: lgtm, release-note-none, size/M

#8 Fix(dockerfile): add yarn build in dockerfile
  Dockerfile
Labels: lgtm, release-note-none, size/XS

#9 perf(dockerfile): modify the docker build method
  Dockerfile
Labels: lgtm, release-note-none, size/XS

#10 Fix(manifest): fix service template lint to deploy
  manifests/klever-web/templates/service.yaml
Labels: release-note-none, size/S

#11 fix(dockerfile): Update dockerfile and file name
  .dockerignore
  src/components/log/header.tsx
  src/components/log/logUI.tsx
  src/components/log/scrollButton.tsx
  src/components/log/webSocket.ts
Labels: release-note-action-required, release-note-none, size/S
